spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/resa
spring.datasource.username=resa
spring.datasource.password=resa_dev
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
